import { Price } from "@/components/currency";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getProducts } from "@/lib/catalog";
import { ProductOptions } from "@/components/store";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const p = (await getProducts()).find((p) => p.id === slug); return { title: p?.name || "Piece not found" }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const p = (await getProducts()).find((p) => p.id === slug); if (!p) notFound(); return <><div className="breadcrumb"><Link href="/shop">Shop</Link> / {p.category} / {p.name}</div><section className="product-detail"><div className="detail-image"><Image src={p.image || "/images/placeholder.svg"} unoptimized={p.image.startsWith("https://")} alt={`${p.name} in ${p.color}`} fill priority sizes="(max-width: 700px) 90vw, 45vw"/></div><div className="detail-copy"><span className="eyebrow">{p.category.toUpperCase()} · HANDMADE WITH LOVE</span><h1>{p.name}</h1><p className="price"><Price product={p}/></p><p>{p.description}</p><ProductOptions product={p}/><details><summary>Materials & care</summary><p>Care details will be confirmed with the final product listing. As a general starting point, handle crochet gently and store folded to help preserve its shape.</p></details><details><summary>Delivery & returns</summary><p>Delivery availability and lead times will be confirmed when the store opens. See our <Link className="text-link" href="/returns">return policy</Link> for the current preview information.</p></details><p className="notice">{process.env.API_BASE_URL ? "Online ordering is not open yet. Contact us about this piece." : "Preview piece with an illustrative image and sample price. Ordering is not open yet."}</p></div></section></>; }
